resolver: lts-15.15

flags: {}

packages:
- '.'

extra-deps:
- haskus-binary-1.5
- haskus-utils-1.5
- haskus-utils-compat-1.1
- haskus-utils-data-1.3
- haskus-utils-types-1.5
- haskus-utils-variant-3.0
- hsnoise-0.0.2
- git: https://github.com/haskus/packages.git
  commit: e92231d1b6d70144c7f04cae07b8c3614dde05d2
  subdirs:
     - haskus-web
     - haskus-ui
- git: https://github.com/haskus/haskus-system.git
  commit: 38b3a363c26bc4d82e3493d8638d46bc35678616
  subdirs:
      - haskus-system

flags:
   diagrams:
      rasterific: true

ghc-options:
   "haskus-system": -fobject-code
   "$locals": -fhide-source-paths
